name: CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: Install Dependencies
              run: npm ci

            - name: Lint Code
              run: npm run lint

            - name: Run Tests
              run: npm run test:ci

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              id: build_and_push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

            - name: Scan image with Grype
              uses: anchore/scan-action@v3
              with:
                  image: 'ghcr.io/${{ github.repository }}:${{ github.sha }}'
                  fail-build: true
                  severity-cutoff: high
